version: "3.9"

services:

  rabbitmq:
    image: rabbitmq
    env_file:
      - .env

  postgres-db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5961:5432

  web:
    build: .
    image: djangodb_marinecv
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
      - static:/static 
      - media:/media
    depends_on:
      - postgres-db
      - rabbitmq
    env_file:
      - .env
    command: "/bin/bash -c 'pip install -r requirements.txt; invoke run'"

  celery:
    build: .
    image: djangodb_marinecv
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
      - static:/static 
      - media:/media
    depends_on:
      - postgres-db
      - rabbitmq
    env_file:
      - .env
    command: "celery -A config.celery.app worker"

  nginx:
    image: nginx
    links:
      - web:web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static:ro
      - media:/media:ro
    networks:
      - default
      - proxy_2
    environment:
      - VIRTUAL_HOST=cvsender.vbelinskaya.com
      - LETSENCRYPT_HOST=cvsender.vbelinskaya.com

networks:
  default:
  proxy_2:
    external: true
      
volumes:
  pgdata: {}
  static: {}
  media: {}
