# Generated by Django 4.0.6 on 2022-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('link', models.URLField(null=True, verbose_name='link')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='email')),
                ('cadet', models.BooleanField(default=False, verbose_name='cadet')),
                ('container', models.BooleanField(default=False, verbose_name='container')),
                ('bulk', models.BooleanField(default=False, verbose_name='bulk')),
                ('tanker', models.BooleanField(default=False, verbose_name='tanker')),
                ('chemical_tanker', models.BooleanField(default=False, verbose_name='chemical_tanker')),
                ('product_tanker', models.BooleanField(default=False, verbose_name='product_tanker')),
                ('gas_carrier', models.BooleanField(default=False, verbose_name='gas_carrier')),
                ('lng', models.BooleanField(default=False, verbose_name='lng')),
                ('lpg', models.BooleanField(default=False, verbose_name='lpg')),
                ('reefer', models.BooleanField(default=False, verbose_name='reefer')),
                ('ro_ro', models.BooleanField(default=False, verbose_name='ro_ro')),
                ('heavy_lift', models.BooleanField(default=False, verbose_name='heavy_lift')),
                ('passenger', models.BooleanField(default=False, verbose_name='passenger')),
                ('off_shore', models.BooleanField(default=False, verbose_name='off_shore')),
                ('ferry', models.BooleanField(default=False, verbose_name='ferry')),
                ('tug', models.BooleanField(default=False, verbose_name='tug')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
