# Generated by Django 4.0.6 on 2022-08-04 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvsender', '0002_company_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_from_email', models.EmailField(max_length=200, null=True, verbose_name='send_from_email')),
                ('cv', models.CharField(max_length=255, null=True, verbose_name='cv')),
                ('text', models.CharField(max_length=255, null=True, verbose_name='text')),
                ('selected_companies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cvsender.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
