# Generated by Django 4.0.6 on 2022-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsender', '0003_userselectedcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectedcompany',
            name='selected_companies',
        ),
        migrations.AddField(
            model_name='userselectedcompany',
            name='selected_companies',
            field=models.ManyToManyField(related_name='selected_companies', to='cvsender.company'),
        ),
    ]
