# Generated by Django 4.0.6 on 2022-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsender', '0005_alter_userselectedcompany_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectedcompany',
            name='cv',
            field=models.FileField(null=True, upload_to='', verbose_name='cv'),
        ),
    ]
